import type { Metadata } from 'next' 
import './globals.css'
import StyledComponentsRegistry from './registry'
import Navbar from '@/components/Navbar'
  
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
 
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html>
      <body>
        <StyledComponentsRegistry>
        <Navbar/>
          {children}
        </StyledComponentsRegistry>
      </body>
    </html>
  )
}